package com.zhixing.mapper;
import com.baomidou.mybatisplus.core.mapper.BaseMapper;import com.zhixing.entity.ResourceScheduleEntity;import com.zhixing.model.*;import org.apache.ibatis.annotations.*;import java.time.Instant;import java.util.*;
@Mapper
public interface ResourceScheduleMapper extends BaseMapper<ResourceScheduleEntity> {
 @Select({"<script>","SELECT s.id,s.name,s.resource_kind resourceKind,s.keywords,s.weekdays_mask weekdaysMask,s.minute_of_day minuteOfDay,s.timezone,s.per_run_limit perRunLimit,s.state,s.next_run_at nextRunAt,s.version_no versionNo,s.topics_json topicsJson,CASE WHEN s.dedup_enabled=1 THEN TRUE ELSE FALSE END dedupEnabled,CASE WHEN s.summary_enabled=1 THEN TRUE ELSE FALSE END summaryEnabled,",
 "(SELECT r.state FROM resource_run r WHERE r.schedule_id=s.id ORDER BY r.created_at DESC LIMIT 1) lastRunState,(SELECT r.result_count FROM resource_run r WHERE r.schedule_id=s.id ORDER BY r.created_at DESC LIMIT 1) lastResultCount,(SELECT r.created_at FROM resource_run r WHERE r.schedule_id=s.id ORDER BY r.created_at DESC LIMIT 1) lastRunAt ",
 "FROM resource_schedule s WHERE s.owner_id=#{ownerId} AND s.state&lt;&gt;'deleted' ","<if test=\"state != null and state != '' and state != 'all'\">AND s.state=#{state} </if>","ORDER BY s.created_at DESC","</script>"}) List<ResourceScheduleView> selectViews(@Param("ownerId")String ownerId,@Param("state")String state);
 @Select("SELECT s.id,s.name,s.resource_kind resourceKind,s.keywords,s.weekdays_mask weekdaysMask,s.minute_of_day minuteOfDay,s.timezone,s.per_run_limit perRunLimit,s.state,s.next_run_at nextRunAt,s.version_no versionNo,s.topics_json topicsJson,CASE WHEN s.dedup_enabled=1 THEN TRUE ELSE FALSE END dedupEnabled,CASE WHEN s.summary_enabled=1 THEN TRUE ELSE FALSE END summaryEnabled FROM resource_schedule s WHERE s.owner_id=#{ownerId} AND s.id=#{id} AND s.state<>'deleted'") ResourceScheduleView selectView(@Param("ownerId")String ownerId,@Param("id")String id);
 @Select("SELECT * FROM resource_schedule WHERE owner_id=#{ownerId} AND id=#{id} AND state<>'deleted' FOR UPDATE") ResourceScheduleEntity selectOwnedForUpdate(@Param("ownerId")String ownerId,@Param("id")String id);
 @Select("SELECT id,name FROM content_source WHERE enabled=1 ORDER BY name,id") List<ResourceSourceView> selectSources();
 @Select("SELECT source_id FROM resource_schedule_source WHERE schedule_id=#{id} ORDER BY source_id") List<String> selectSourceIds(@Param("id")String id);
 @Select("SELECT cs.name FROM resource_schedule_source ss JOIN content_source cs ON cs.id=ss.source_id WHERE ss.schedule_id=#{id} ORDER BY cs.name") List<String> selectSourceNames(@Param("id")String id);
 @Delete("DELETE FROM resource_schedule_source WHERE schedule_id=#{id}") int deleteSources(@Param("id")String id);
 @Insert("INSERT INTO resource_schedule_source(id,schedule_id,source_id,created_at,updated_at) VALUES(#{rowId},#{scheduleId},#{sourceId},#{now},#{now})") int insertSource(@Param("rowId")String rowId,@Param("scheduleId")String scheduleId,@Param("sourceId")String sourceId,@Param("now")Instant now);
 @Update("UPDATE resource_schedule SET name=#{name},resource_kind=#{kind},keywords=#{keywords},weekdays_mask=#{mask},minute_of_day=#{minute},per_run_limit=#{limit},state=#{state},next_run_at=#{next},version_no=version_no+1,dedup_enabled=#{dedup},summary_enabled=#{summary},topics_json=#{topics},updated_at=#{now} WHERE id=#{id} AND owner_id=#{ownerId} AND version_no=#{version} AND state<>'deleted'") int updateSchedule(@Param("id")String id,@Param("ownerId")String ownerId,@Param("name")String name,@Param("kind")String kind,@Param("keywords")String keywords,@Param("mask")Integer mask,@Param("minute")Integer minute,@Param("limit")Integer limit,@Param("state")String state,@Param("next")Instant next,@Param("dedup")Integer dedup,@Param("summary")Integer summary,@Param("topics")String topics,@Param("now")Instant now,@Param("version")Integer version);
 @Update("UPDATE resource_schedule SET state=#{state},next_run_at=#{next},version_no=version_no+1,updated_at=#{now} WHERE id=#{id} AND owner_id=#{ownerId} AND version_no=#{version} AND state<>'deleted'") int updateState(@Param("id")String id,@Param("ownerId")String ownerId,@Param("state")String state,@Param("next")Instant next,@Param("now")Instant now,@Param("version")Integer version);
}
