-- 知行日课 V3.14：短文点词词汇表（MySQL 5.7.25）
-- 覆盖 V3.13 预置短文中的全部 104 个英文词形；正式词库存在同词时由正式词库优先。
SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci;
SET SESSION time_zone = '+00:00';

CREATE TABLE IF NOT EXISTS `article_word_glossary` (
  `id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `term` VARCHAR(80) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `phonetic` VARCHAR(200) NOT NULL,
  `meaning` VARCHAR(500) NOT NULL,
  `audio_asset_id` CHAR(32) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `audio_voice` VARCHAR(64) CHARACTER SET ascii COLLATE ascii_bin NULL,
  `audio_generated_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`), UNIQUE KEY `uk_article_word_glossary_term` (`term`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='短文点词补充词汇；正式词库优先';

INSERT INTO `article_word_glossary` (`id`,`term`,`phonetic`,`meaning`) VALUES
(MD5('article-glossary:a'),'a','/ə; eɪ/','一个；一'),
(MD5('article-glossary:accepting'),'accepting','/əkˈseptɪŋ/','接受；接纳'),
(MD5('article-glossary:and'),'and','/ənd/','和；并且'),
(MD5('article-glossary:anna'),'anna','/ˈænə/','安娜（人名）'),
(MD5('article-glossary:another'),'another','/əˈnʌðə(r)/','另一个；又一个'),
(MD5('article-glossary:answer'),'answer','/ˈɑːnsə(r)/','答案；回答'),
(MD5('article-glossary:asks'),'asks','/ɑːsks/','询问；请求'),
(MD5('article-glossary:before'),'before','/bɪˈfɔː(r)/','在……以前'),
(MD5('article-glossary:ben'),'ben','/ben/','本（人名）'),
(MD5('article-glossary:calmly'),'calmly','/ˈkɑːmli/','平静地；从容地'),
(MD5('article-glossary:careful'),'careful','/ˈkeəfl/','仔细的；谨慎的'),
(MD5('article-glossary:carefully'),'carefully','/ˈkeəfəli/','仔细地；谨慎地'),
(MD5('article-glossary:change'),'change','/tʃeɪndʒ/','变化；改变'),
(MD5('article-glossary:checks'),'checks','/tʃeks/','检查；核对'),
(MD5('article-glossary:chooses'),'chooses','/ˈtʃuːzɪz/','选择'),
(MD5('article-glossary:classroom'),'classroom','/ˈklɑːsruːm/','教室'),
(MD5('article-glossary:cleans'),'cleans','/kliːnz/','清洁；打扫'),
(MD5('article-glossary:clear'),'clear','/klɪə(r)/','清楚的；明确的'),
(MD5('article-glossary:compares'),'compares','/kəmˈpeəz/','比较'),
(MD5('article-glossary:confidence'),'confidence','/ˈkɒnfɪdəns/','信心；自信'),
(MD5('article-glossary:continue'),'continue','/kənˈtɪnjuː/','继续'),
(MD5('article-glossary:corner'),'corner','/ˈkɔːnə(r)/','角落'),
(MD5('article-glossary:day'),'day','/deɪ/','一天；白天'),
(MD5('article-glossary:decision'),'decision','/dɪˈsɪʒn/','决定'),
(MD5('article-glossary:detail'),'detail','/ˈdiːteɪl/','细节'),
(MD5('article-glossary:easier'),'easier','/ˈiːziə(r)/','更容易的'),
(MD5('article-glossary:emma'),'emma','/ˈemə/','艾玛（人名）'),
(MD5('article-glossary:ends'),'ends','/endz/','结束'),
(MD5('article-glossary:evidence'),'evidence','/ˈevɪdəns/','证据'),
(MD5('article-glossary:example'),'example','/ɪɡˈzɑːmpl/','例子；示例'),
(MD5('article-glossary:explain'),'explain','/ɪkˈspleɪn/','解释'),
(MD5('article-glossary:explains'),'explains','/ɪkˈspleɪnz/','解释；说明'),
(MD5('article-glossary:feels'),'feels','/fiːlz/','感到；感觉'),
(MD5('article-glossary:finds'),'finds','/faɪndz/','找到；发现'),
(MD5('article-glossary:finishes'),'finishes','/ˈfɪnɪʃɪz/','完成；结束'),
(MD5('article-glossary:first'),'first','/fɜːst/','第一；首先'),
(MD5('article-glossary:follows'),'follows','/ˈfɒləʊz/','跟随；遵循'),
(MD5('article-glossary:friend'),'friend','/frend/','朋友'),
(MD5('article-glossary:from'),'from','/frɒm/','来自；从'),
(MD5('article-glossary:garden'),'garden','/ˈɡɑːdn/','花园'),
(MD5('article-glossary:helpful'),'helpful','/ˈhelpfl/','有帮助的'),
(MD5('article-glossary:helps'),'helps','/helps/','帮助'),
(MD5('article-glossary:home'),'home','/həʊm/','家；家里'),
(MD5('article-glossary:idea'),'idea','/aɪˈdɪə/','想法；主意'),
(MD5('article-glossary:ideas'),'ideas','/aɪˈdɪəz/','想法；观点（复数）'),
(MD5('article-glossary:in'),'in','/ɪn/','在……里面'),
(MD5('article-glossary:instead'),'instead','/ɪnˈsted/','反而；代替'),
(MD5('article-glossary:jack'),'jack','/dʒæk/','杰克（人名）'),
(MD5('article-glossary:kitchen'),'kitchen','/ˈkɪtʃɪn/','厨房'),
(MD5('article-glossary:learner'),'learner','/ˈlɜːnə(r)/','学习者'),
(MD5('article-glossary:learns'),'learns','/lɜːnz/','学习；学会'),
(MD5('article-glossary:leaving'),'leaving','/ˈliːvɪŋ/','离开'),
(MD5('article-glossary:leo'),'leo','/ˈliːəʊ/','利奥（人名）'),
(MD5('article-glossary:library'),'library','/ˈlaɪbrəri/','图书馆'),
(MD5('article-glossary:lily'),'lily','/ˈlɪli/','莉莉（人名）'),
(MD5('article-glossary:lucy'),'lucy','/ˈluːsi/','露西（人名）'),
(MD5('article-glossary:main'),'main','/meɪn/','主要的'),
(MD5('article-glossary:makes'),'makes','/meɪks/','制作；使得'),
(MD5('article-glossary:map'),'map','/mæp/','地图'),
(MD5('article-glossary:mia'),'mia','/ˈmiːə/','米娅（人名）'),
(MD5('article-glossary:mistake'),'mistake','/mɪˈsteɪk/','错误'),
(MD5('article-glossary:museum'),'museum','/mjuˈziːəm/','博物馆'),
(MD5('article-glossary:new'),'new','/njuː/','新的'),
(MD5('article-glossary:next'),'next','/nekst/','下一个；接下来的'),
(MD5('article-glossary:nina'),'nina','/ˈniːnə/','妮娜（人名）'),
(MD5('article-glossary:note'),'note','/nəʊt/','笔记；记录'),
(MD5('article-glossary:of'),'of','/əv/','……的'),
(MD5('article-glossary:one'),'one','/wʌn/','一；一个'),
(MD5('article-glossary:park'),'park','/pɑːk/','公园'),
(MD5('article-glossary:picture'),'picture','/ˈpɪktʃə(r)/','图片；画面'),
(MD5('article-glossary:playground'),'playground','/ˈpleɪɡraʊnd/','操场；游乐场'),
(MD5('article-glossary:practices'),'practices','/ˈpræktɪsɪz/','练习'),
(MD5('article-glossary:process'),'process','/ˈprəʊses/','过程；流程'),
(MD5('article-glossary:question'),'question','/ˈkwestʃən/','问题'),
(MD5('article-glossary:quiet'),'quiet','/ˈkwaɪət/','安静的'),
(MD5('article-glossary:reads'),'reads','/riːdz/','阅读'),
(MD5('article-glossary:ready'),'ready','/ˈredi/','准备好的'),
(MD5('article-glossary:records'),'records','/rɪˈkɔːdz/','记录'),
(MD5('article-glossary:remembers'),'remembers','/rɪˈmembəz/','记得；记住'),
(MD5('article-glossary:result'),'result','/rɪˈzʌlt/','结果'),
(MD5('article-glossary:ryan'),'ryan','/ˈraɪən/','瑞恩（人名）'),
(MD5('article-glossary:sentence'),'sentence','/ˈsentəns/','句子'),
(MD5('article-glossary:shares'),'shares','/ʃeəz/','分享'),
(MD5('article-glossary:shop'),'shop','/ʃɒp/','商店'),
(MD5('article-glossary:short'),'short','/ʃɔːt/','短的'),
(MD5('article-glossary:simple'),'simple','/ˈsɪmpl/','简单的'),
(MD5('article-glossary:small'),'small','/smɔːl/','小的'),
(MD5('article-glossary:station'),'station','/ˈsteɪʃn/','车站'),
(MD5('article-glossary:step'),'step','/step/','步骤；一步'),
(MD5('article-glossary:steps'),'steps','/steps/','步骤（复数）'),
(MD5('article-glossary:task'),'task','/tɑːsk/','任务'),
(MD5('article-glossary:the'),'the','/ðə; ðiː/','这；该（定冠词）'),
(MD5('article-glossary:three'),'three','/θriː/','三'),
(MD5('article-glossary:to'),'to','/tə; tuː/','向；到；用于不定式'),
(MD5('article-glossary:today'),'today','/təˈdeɪ/','今天'),
(MD5('article-glossary:tom'),'tom','/tɒm/','汤姆（人名）'),
(MD5('article-glossary:two'),'two','/tuː/','二；两个'),
(MD5('article-glossary:useful'),'useful','/ˈjuːsfl/','有用的'),
(MD5('article-glossary:visits'),'visits','/ˈvɪzɪts/','参观；拜访'),
(MD5('article-glossary:watches'),'watches','/ˈwɒtʃɪz/','观看；观察'),
(MD5('article-glossary:while'),'while','/waɪl/','当……时；一段时间'),
(MD5('article-glossary:with'),'with','/wɪð/','和；带有'),
(MD5('article-glossary:working'),'working','/ˈwɜːkɪŋ/','工作；正在工作的'),
(MD5('article-glossary:writes'),'writes','/raɪts/','书写；写下')
ON DUPLICATE KEY UPDATE `phonetic`=VALUES(`phonetic`),`meaning`=VALUES(`meaning`),`updated_at`=CURRENT_TIMESTAMP(3);

SELECT COUNT(*) AS glossary_count FROM article_word_glossary;
