-- Additive migration. Cards belong to an exact word version; no automatic cross-version reuse.
CREATE TABLE IF NOT EXISTS word_learning_card (
 id CHAR(32) NOT NULL PRIMARY KEY,
 content_version_id CHAR(32) NOT NULL,
 card_key VARCHAR(80) NOT NULL,
 card_type VARCHAR(24) NOT NULL,
 sense_label VARCHAR(160) NOT NULL,
 title VARCHAR(160) NOT NULL,
 related_term VARCHAR(80) NULL,
 body VARCHAR(1200) NOT NULL,
 example_text VARCHAR(500) NULL,
 example_translation VARCHAR(500) NULL,
 recall_prompt VARCHAR(300) NULL,
 source_kind VARCHAR(24) NOT NULL DEFAULT 'original',
 source_title VARCHAR(200) NOT NULL,
 source_url VARCHAR(2048) NULL,
 source_locator VARCHAR(200) NULL,
 source_verified SMALLINT NOT NULL DEFAULT 0,
 rights_status VARCHAR(24) NOT NULL DEFAULT 'unknown',
 rights_note VARCHAR(1000) NULL,
 review_status VARCHAR(24) NOT NULL DEFAULT 'draft',
 reviewed_by VARCHAR(80) NULL,
 reviewed_at TIMESTAMP(3) NULL DEFAULT NULL,
 state VARCHAR(24) NOT NULL DEFAULT 'draft',
 sort_no INT NOT NULL DEFAULT 0,
 del_is SMALLINT NOT NULL DEFAULT 0,
 created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
 UNIQUE KEY uk_word_card_version_key(content_version_id,card_key),
 KEY idx_word_card_public(content_version_id,del_is,state,review_status,sort_no)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
