package com.zhixing.service;

import com.alibaba.nls.client.AccessToken;
import com.zhixing.common.ApiException;
import com.zhixing.common.CryptoUtils;
import com.zhixing.config.AppProperties;
import com.zhixing.dto.TtsConfigRequest;
import org.springframework.http.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;

@Service
public class AliyunTtsService {
    private static final String APP_KEY="ALIYUN_NLS_APP_KEY",AK_ID="ALIYUN_AK_ID",AK_SECRET="ALIYUN_AK_SECRET";
    private static final String PREVIEW_TEXT="The quick brown fox jumps over the lazy dog.";
    private static final Map<String,VoiceDefinition> VOCABULARY_VOICES=voiceCatalog();
    private final JdbcTemplate jdbc;private final AppParameterService parameters;private final MediaService media;private final RestTemplate http;private final AppProperties properties;
    private final Map<String,Object> locks=new ConcurrentHashMap<String,Object>();
    private volatile String token;private volatile long tokenExpiresAt;
    public AliyunTtsService(JdbcTemplate jdbc,AppParameterService parameters,MediaService media,RestTemplate http,AppProperties properties){this.jdbc=jdbc;this.parameters=parameters;this.media=media;this.http=http;this.properties=properties;}

    public Map<String,Object> adminConfig(){Map<String,Object> result=new LinkedHashMap<String,Object>();result.put("provider","aliyun_nls");result.put("endpoint",parameters.optional("tts.aliyun.endpoint","https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/tts"));result.put("voice",parameters.optional("tts.aliyun.voice","aixia"));result.put("sampleRate",integer(parameters.optional("tts.aliyun.sample_rate","16000"),16000));result.put("appKeyConfigured",parameters.configured(APP_KEY));result.put("accessKeyIdConfigured",parameters.configured(AK_ID));result.put("accessKeySecretConfigured",parameters.configured(AK_SECRET));result.put("ready",configured());result.put("logs",jdbc.queryForList("SELECT id,target_type,target_id,provider_code,voice,char_count,state,provider_request_id,asset_id,error_code,created_at FROM tts_usage_log ORDER BY created_at DESC LIMIT 100"));return result;}

    @Transactional
    public Map<String,Object> saveConfig(TtsConfigRequest request){String endpoint=clean(request.getEndpoint());if(!endpoint.matches("https://nls-gateway-[a-z0-9-]+\\.aliyuncs\\.com/(stream|rest)/.*"))throw bad("INVALID_TTS_ENDPOINT","只允许阿里云 NLS HTTPS 地址");int sample=request.getSampleRate()==null?16000:request.getSampleRate();if(sample!=8000&&sample!=16000)throw bad("INVALID_TTS_SAMPLE_RATE","采样率只能是 8000 或 16000");parameters.saveValue("tts.aliyun.endpoint",endpoint,"Aliyun NLS TTS endpoint");parameters.saveValue("tts.aliyun.voice",clean(request.getVoice()),"Aliyun NLS English voice");parameters.saveValue("tts.aliyun.sample_rate",String.valueOf(sample),"Aliyun NLS sample rate");parameters.saveSecret(APP_KEY,request.getAppKey());parameters.saveSecret(AK_ID,request.getAccessKeyId());parameters.saveSecret(AK_SECRET,request.getAccessKeySecret());token=null;tokenExpiresAt=0;return adminConfig();}

    public boolean configured(){return parameters.configured(APP_KEY)&&parameters.configured(AK_ID)&&parameters.configured(AK_SECRET);}

    /** 词库批次只暴露已按英语口音分组的阿里云 NLS 预设音色，避免任意参数进入任务快照。 */
    public List<Map<String,Object>> vocabularyVoices(){List<Map<String,Object>> result=new ArrayList<Map<String,Object>>();for(VoiceDefinition voice:VOCABULARY_VOICES.values()){Map<String,Object> item=new LinkedHashMap<String,Object>();item.put("code",voice.code);item.put("name",voice.name);item.put("accent",voice.accent);item.put("gender",voice.gender);item.put("label",voice.name+" · "+voice.gender);result.add(item);}return result;}
    public String vocabularyVoice(Object requested,String accent,String fallback){String code=clean(requested==null?fallback:String.valueOf(requested)).toLowerCase(Locale.ROOT);VoiceDefinition voice=requiredVocabularyVoice(code);if(!accent.equals(voice.accent))throw bad("INVALID_VOCABULARY_ACCENT","所选音色与目标口音不匹配");return voice.code;}

    /** 试听仅在内存中合成并以内联音频返回，不创建 media_asset、TTS 任务或审计发布数据。 */
    public Map<String,Object> previewVocabularyVoice(String voice,Integer sampleRate){VoiceDefinition selected=requiredVocabularyVoice(voice);int rate=validSampleRate(sampleRate==null?16000:sampleRate);Synthesis audio=synthesize(PREVIEW_TEXT,selected.code,rate);Map<String,Object> result=new LinkedHashMap<String,Object>();result.put("voice",selected.code);result.put("sampleRate",rate);result.put("audioDataUrl","data:audio/mpeg;base64,"+Base64.getEncoder().encodeToString(audio.bytes));return result;}

    /** 供词库批处理使用：先合成到内存，再以稳定 key 直接写入 OSS。 */
    public String synthesizeVocabularyAudio(String text,String voice,String purpose,String objectKey,String originUrl,String licenseNote){
        return synthesizeVocabularyAudio(text,voice,purpose,objectKey,originUrl,licenseNote,integer(parameters.optional("tts.aliyun.sample_rate","16000"),16000));
    }
    public String synthesizeVocabularyAudio(String text,String voice,String purpose,String objectKey,String originUrl,String licenseNote,int sampleRate){
        if(text==null||text.trim().isEmpty())throw bad("TTS_TEXT_EMPTY","语音文本不能为空");
        if(text.codePointCount(0,text.length())>300)throw bad("TTS_TEXT_TOO_LONG","单词或例句超过 300 字符，需要先拆分");
        Synthesis audio=synthesize(text,requiredVocabularyVoice(voice).code,validSampleRate(sampleRate));
        return media.storeVocabularyAudio(purpose,objectKey,audio.bytes,originUrl,licenseNote);
    }

    public Map<String,Object> speech(String ownerId,String contentId){Map<String,Object> row=content(contentId);String type=string(row,"content_type");boolean article="english_article".equals(type),glossary="glossary_word".equals(type);if(!article&&!"word".equals(type)&&!glossary)throw bad("TTS_TARGET_UNSUPPORTED","只支持英语短文和单词朗读");String versionId=string(row,"version_id"),targetId=glossary?string(row,"glossary_id"):contentId,logType=article?"english_article":"word",voice=parameters.optional("tts.aliyun.voice","aixia");String cached=cached(row,type,versionId,voice);if(cached!=null)return result(cached,voice,true);
        Object lock=locks.computeIfAbsent(type+":"+versionId+":"+voice,key->new Object());synchronized(lock){try{row=content(contentId);cached=cached(row,type,versionId,voice);if(cached!=null)return result(cached,voice,true);String text=article?string(row,"body"):string(row,"word_term");if(text==null||text.trim().isEmpty())throw bad("TTS_TEXT_EMPTY","朗读文本为空");int chars=text.codePointCount(0,text.length());if(chars>300)throw bad("TTS_TEXT_TOO_LONG","当前短文超过 300 字符，请在管理端拆分后再生成音频");Synthesis audio=synthesize(text,voice);String assetId=media.storePublicAudio(article?"article_audio":"word_audio","tts/"+type,audio.bytes,"audio/mpeg","aliyun_nls","Aliyun NLS generated speech");if(article)jdbc.update("UPDATE content_version SET article_audio_asset_id=?,article_audio_voice=?,article_audio_generated_at=CURRENT_TIMESTAMP WHERE id=?",assetId,voice,versionId);else if(glossary)jdbc.update("UPDATE article_word_glossary SET audio_asset_id=?,audio_voice=?,audio_generated_at=CURRENT_TIMESTAMP,updated_at=CURRENT_TIMESTAMP WHERE id=?",assetId,voice,versionId);else{String target="tts:"+shortHash(voice);jdbc.update("DELETE FROM pronunciation WHERE content_version_id=? AND target_key=?",versionId,target);jdbc.update("INSERT INTO pronunciation(id,content_version_id,target_key,accent,asset_id,state) VALUES(?,?,?,?,?,'ready')",CryptoUtils.randomId(),versionId,target,"tts",assetId);}log(ownerId,logType,targetId,versionId,voice,chars,"succeeded",audio.requestId,assetId,null);return result(media.referenceUrl(assetId),voice,false);}catch(ApiException e){log(ownerId,logType,targetId,versionId,voice,0,"failed",null,null,e.getCode());throw e;}catch(RuntimeException e){log(ownerId,logType,targetId,versionId,voice,0,"failed",null,null,"TTS_PROVIDER_ERROR");throw new ApiException(HttpStatus.BAD_GATEWAY,"TTS_PROVIDER_ERROR","语音合成失败，请稍后重试");}finally{locks.remove(type+":"+versionId+":"+voice,lock);}}
    }

    private Synthesis synthesize(String text,String voice){return synthesize(text,voice,integer(parameters.optional("tts.aliyun.sample_rate","16000"),16000));}
    private Synthesis synthesize(String text,String voice,int sampleRate){if(properties.getTts().isMockEnabled())return new Synthesis("mock" ,("ID3"+text).getBytes(StandardCharsets.UTF_8));if(!configured())throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"TTS_NOT_CONFIGURED","请先在 Web 管理端配置阿里云 TTS");Map<String,Object> body=new LinkedHashMap<String,Object>();body.put("appkey",parameters.required(APP_KEY));body.put("token",accessToken());body.put("text",text);body.put("format","mp3");body.put("sample_rate",sampleRate);body.put("voice",voice);body.put("speech_rate",0);HttpHeaders headers=new HttpHeaders();headers.setContentType(MediaType.APPLICATION_JSON);ResponseEntity<byte[]> response=http.exchange(parameters.optional("tts.aliyun.endpoint","https://nls-gateway-cn-shanghai.aliyuncs.com/stream/v1/tts"),HttpMethod.POST,new HttpEntity<Map<String,Object>>(body,headers),byte[].class);MediaType type=response.getHeaders().getContentType();if(!response.getStatusCode().is2xxSuccessful()||type==null||!"audio".equalsIgnoreCase(type.getType())||response.getBody()==null||response.getBody().length==0)throw new ApiException(HttpStatus.BAD_GATEWAY,"TTS_PROVIDER_REJECTED","阿里云未返回可用音频");return new Synthesis(response.getHeaders().getFirst("task_id"),response.getBody());}
    private synchronized String accessToken(){long now=Instant.now().getEpochSecond();if(token!=null&&tokenExpiresAt-now>300)return token;try{AccessToken request=new AccessToken(parameters.required(AK_ID),parameters.required(AK_SECRET),"nls-meta.cn-shanghai.aliyuncs.com","cn-shanghai","2019-02-28");request.apply();token=request.getToken();tokenExpiresAt=request.getExpireTime();if(token==null||token.isEmpty())throw new IllegalStateException("empty token");return token;}catch(LinkageError e){throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"TTS_CLIENT_INCOMPATIBLE","TTS 客户端依赖冲突，请重新构建并重启后端");}catch(Exception e){throw new ApiException(HttpStatus.SERVICE_UNAVAILABLE,"TTS_TOKEN_FAILED","阿里云 TTS 鉴权失败，请检查 AccessKey 权限");}}
    private Map<String,Object> content(String id){if(id!=null&&id.startsWith("glossary:")){String term=id.substring("glossary:".length()).toLowerCase(Locale.ROOT);if(!term.matches("[a-z]+"))throw new ApiException(HttpStatus.NOT_FOUND,"CONTENT_NOT_FOUND","短文词汇不存在");List<Map<String,Object>> glossary=jdbc.queryForList("SELECT 'glossary_word' content_type,id version_id,id glossary_id,term word_term,audio_asset_id glossary_audio_asset_id,audio_voice glossary_audio_voice FROM article_word_glossary WHERE term=?",term);if(glossary.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"CONTENT_NOT_FOUND","短文词汇不存在");return glossary.get(0);}List<Map<String,Object>> rows=jdbc.queryForList("SELECT lc.content_type,cv.id version_id,cv.body,cv.word_term,cv.article_audio_asset_id,cv.article_audio_voice FROM learning_content lc JOIN content_version cv ON cv.id=lc.published_version_id WHERE lc.id=? AND lc.state='published'",id);if(rows.isEmpty())throw new ApiException(HttpStatus.NOT_FOUND,"CONTENT_NOT_FOUND","学习内容不存在");return rows.get(0);}
    private String cached(Map<String,Object> row,String type,String versionId,String voice){String assetId=null;if("english_article".equals(type)&&voice.equals(string(row,"article_audio_voice")))assetId=string(row,"article_audio_asset_id");if("glossary_word".equals(type)&&voice.equals(string(row,"glossary_audio_voice")))assetId=string(row,"glossary_audio_asset_id");if("word".equals(type)){String target="tts:"+shortHash(voice);List<String> ids=jdbc.query("SELECT p.asset_id FROM pronunciation p JOIN media_asset m ON m.id=p.asset_id AND m.state='ready' WHERE p.content_version_id=? AND p.target_key=? AND p.state='ready' LIMIT 1",(rs,n)->rs.getString(1),versionId,target);if(!ids.isEmpty())assetId=ids.get(0);}if(assetId==null)return null;Integer count=jdbc.queryForObject("SELECT COUNT(*) FROM media_asset WHERE id=? AND state='ready'",Integer.class,assetId);return count!=null&&count>0?media.referenceUrl(assetId):null;}
    private void log(String owner,String type,String target,String version,String voice,int chars,String state,String request,String asset,String error){jdbc.update("INSERT INTO tts_usage_log(id,owner_id,target_type,target_id,content_version_id,provider_code,voice,char_count,state,provider_request_id,asset_id,error_code) VALUES(?,?,?,?,?,'aliyun_nls',?,?,?,?,?,?)",CryptoUtils.randomId(),owner,type,target,version,voice,chars,state,request,asset,error);}
    private Map<String,Object> result(String url,String voice,boolean cached){Map<String,Object> r=new LinkedHashMap<String,Object>();r.put("audioUrl",url);r.put("voice",voice);r.put("cached",cached);return r;}
    private static Map<String,VoiceDefinition> voiceCatalog(){Map<String,VoiceDefinition> voices=new LinkedHashMap<String,VoiceDefinition>();addVoice(voices,"eva","Eva","us","美式女声");addVoice(voices,"andy","Andy","us","美式男声");addVoice(voices,"luna","Luna","uk","英式女声");addVoice(voices,"emily","Emily","uk","英式女声");addVoice(voices,"wendy","Wendy","uk","英式女声");addVoice(voices,"olivia","Olivia","uk","英式女声");addVoice(voices,"luca","Luca","uk","英式男声");addVoice(voices,"eric","Eric","uk","英式男声");addVoice(voices,"william","William","uk","英式男声");return Collections.unmodifiableMap(voices);}
    private static void addVoice(Map<String,VoiceDefinition> voices,String code,String name,String accent,String gender){voices.put(code,new VoiceDefinition(code,name,accent,gender));}
    private VoiceDefinition requiredVocabularyVoice(String value){VoiceDefinition voice=VOCABULARY_VOICES.get(clean(value).toLowerCase(Locale.ROOT));if(voice==null)throw bad("UNSUPPORTED_VOCABULARY_VOICE","请选择阿里云 NLS 支持的英语音色");return voice;}
    private int validSampleRate(int sampleRate){if(sampleRate!=8000&&sampleRate!=16000)throw bad("INVALID_TTS_SAMPLE_RATE","采样率只能是 8000 或 16000");return sampleRate;}
    private String shortHash(String value){byte[] bytes=CryptoUtils.sha256(value);StringBuilder hex=new StringBuilder();for(int i=0;i<6;i++)hex.append(String.format("%02x",bytes[i]&255));return hex.toString();}private Object raw(Map<String,Object> row,String key){Object value=row.get(key);return value==null?row.get(key.toUpperCase()):value;}private String string(Map<String,Object> row,String key){Object value=raw(row,key);return value==null?null:String.valueOf(value);}private int integer(String value,int fallback){try{return Integer.parseInt(value);}catch(Exception e){return fallback;}}private String clean(String value){return value==null?"":value.trim();}private ApiException bad(String code,String message){return new ApiException(HttpStatus.BAD_REQUEST,code,message);}private static class VoiceDefinition{final String code,name,accent,gender;VoiceDefinition(String code,String name,String accent,String gender){this.code=code;this.name=name;this.accent=accent;this.gender=gender;}}private static class Synthesis{final String requestId;final byte[] bytes;Synthesis(String requestId,byte[] bytes){this.requestId=requestId;this.bytes=bytes;}}
}
