package com.zhixing.service;

import com.fasterxml.jackson.core.type.TypeReference; import com.fasterxml.jackson.databind.ObjectMapper;
import com.zhixing.common.*; import com.zhixing.dto.TaskEventRequest; import com.zhixing.entity.*; import com.zhixing.mapper.*; import com.zhixing.model.*;
import org.springframework.dao.DuplicateKeyException; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;

/** F04 规则层：数据库访问集中于 Mapper，状态与事件在同一事务提交。 */
@Service public class DailyTaskService {
 private final DailyPackageMapper packages; private final DailyTaskMapper tasks; private final LearningPlanMapper plans; private final MaterialMapper materials; private final ObjectMapper json;
 public DailyTaskService(DailyPackageMapper p,DailyTaskMapper t,LearningPlanMapper l,MaterialMapper m,ObjectMapper j){packages=p;tasks=t;plans=l;materials=m;json=j;}
 public DailyPackageView get(String owner,LocalDate date){DailyPackageEntity p=packages.selectByOwnerAndDate(owner,date);if(p!=null)return view(p,tasks.selectByPackage(p.getId()));LearningPlanEntity plan=plans.selectEffectiveOn(owner,date);if(plan==null||!active(plan,date))return empty(date,"非活动日(不自动安排任务)");return activate(owner,date,false);}
 /** 保存计划后同步尚未完成的今日任务；进行中、已完成、已跳过任务均是事实记录，不予覆盖。 */
 @Transactional public void syncToday(String owner,LearningPlanEntity plan){LocalDate today=LocalDate.now(ZoneId.of("Asia/Shanghai"));DailyPackageEntity p=packages.selectByOwnerAndDateForUpdate(owner,today);if(p==null)return;List<DailyTaskEntity> before=tasks.selectByPackage(p.getId());String beforeJson=snapshot(p,before);p.setPlanId(plan.getId());p.setBudgetSeconds(plan.getDailyBudgetMin()*60);p.setGapJson(gaps(owner,today,plan));p.setVersionNo(p.getVersionNo()+1);List<DailyTaskEntity> desired=generate(p,plan),after=new ArrayList<DailyTaskEntity>(before);for(DailyTaskEntity want:desired){DailyTaskEntity old=find(after,want);if(old==null){tasks.insert(want);after.add(want);}else if(old.getStatus()==DailyTaskStatus.CANCELLED){reopen(old);recordSystemEvent(old,"readd",DailyTaskStatus.CANCELLED,DailyTaskStatus.TODO);}}for(DailyTaskEntity old:after)if(old.getStatus()==DailyTaskStatus.TODO&&!contains(desired,old)){cancel(old);recordSystemEvent(old,"cancel",DailyTaskStatus.TODO,DailyTaskStatus.CANCELLED);}int total=0,done=0;for(DailyTaskEntity task:after)if(task.getStatus()!=DailyTaskStatus.CANCELLED){total++;if(task.getStatus()==DailyTaskStatus.DONE)done++;}p.setCurrentCount(total);p.setFinalDoneCount(done);packages.updateById(p);PackageRevisionEntity revision=new PackageRevisionEntity();revision.setId(CryptoUtils.randomId());revision.setOwnerId(owner);revision.setPackageId(p.getId());revision.setVersionNo(p.getVersionNo());revision.setReason("user_adjust");revision.setBeforeJson(beforeJson);revision.setAfterJson(snapshot(p,after));packages.insertRevision(revision);}
 @Transactional public DailyPackageView activate(String owner,LocalDate date,boolean temporary){DailyPackageEntity prior=packages.selectByOwnerAndDateForUpdate(owner,date);if(prior!=null)return view(prior,tasks.selectByPackage(prior.getId()));LearningPlanEntity plan=plans.selectEffectiveOn(owner,date);if(plan==null)throw fail(HttpStatus.CONFLICT,"PLAN_REQUIRED","请先保存学习计划后再激活今日任务");if(!temporary&&!active(plan,date))return empty(date,"非活动日(不自动安排任务)");try{DailyPackageEntity p=pack(owner,date,plan,temporary);packages.insert(p);List<DailyTaskEntity> made=generate(p,plan);for(DailyTaskEntity t:made)tasks.insert(t);p.setOriginalCount(made.size());p.setCurrentCount(made.size());packages.updateById(p);PackageRevisionEntity r=new PackageRevisionEntity();r.setId(CryptoUtils.randomId());r.setOwnerId(owner);r.setPackageId(p.getId());r.setVersionNo(1);r.setReason("activate");r.setAfterJson(snapshot(p,made));packages.insertRevision(r);return view(p,made);}catch(DuplicateKeyException e){DailyPackageEntity concurrent=packages.selectByOwnerAndDate(owner,date);if(concurrent!=null)return view(concurrent,tasks.selectByPackage(concurrent.getId()));throw e;}}
 @Transactional public DailyTaskView event(String owner,String id,TaskEventRequest r){DailyTaskEntity t=tasks.selectOwnedForUpdate(id,owner);if(t==null)throw fail(HttpStatus.NOT_FOUND,"TASK_NOT_FOUND","任务不存在或无权访问");Transition x=transition(t.getStatus(),r.getEventType());if(r.getExpectedVersion()==t.getVersionNo()-1&&t.getStatus()==x.to)return task(t);if(!r.getExpectedVersion().equals(t.getVersionNo()))throw fail(HttpStatus.CONFLICT,"TASK_VERSION_CONFLICT","任务已变更，请刷新后重试");Instant now=Instant.now(),start=t.getStartedAt(),complete=t.getCompletedAt();if(x.to==DailyTaskStatus.DOING&&start==null)start=now;if(x.to==DailyTaskStatus.DONE)complete=now;else if(x.from==DailyTaskStatus.DONE)complete=null;int next=t.getVersionNo()+1;if(tasks.transition(id,owner,t.getVersionNo(),next,x.to.name(),start,complete)!=1)throw fail(HttpStatus.CONFLICT,"TASK_VERSION_CONFLICT","任务已变更，请刷新后重试");TaskEventEntity e=new TaskEventEntity();e.setId(CryptoUtils.randomId());e.setOwnerId(owner);e.setTaskId(id);e.setTaskVersion(next);e.setEventType(x.event);e.setActorType("user");e.setFromStatus(x.from.name());e.setToStatus(x.to.name());e.setOccurredAt(now);e.setReason(reason(r.getReason()));packages.insertEvent(e);List<DailyTaskEntity> all=tasks.selectByPackage(t.getPackageId());int total=0,done=0;for(DailyTaskEntity a:all){DailyTaskStatus s=a.getId().equals(id)?x.to:a.getStatus();if(s!=DailyTaskStatus.CANCELLED){total++;if(s==DailyTaskStatus.DONE)done++;}}packages.updateMetrics(t.getPackageId(),done,total);t.setStatus(x.to);t.setVersionNo(next);t.setStartedAt(start);t.setCompletedAt(complete);return task(t);}
 private DailyPackageEntity pack(String owner,LocalDate d,LearningPlanEntity p,boolean temp){DailyPackageEntity x=new DailyPackageEntity();x.setId(CryptoUtils.randomId());x.setOwnerId(owner);x.setBusinessDate(d);x.setPlanId(p.getId());x.setState("active");x.setTemporary(temp?1:0);x.setVersionNo(1);x.setBudgetSeconds(p.getDailyBudgetMin()*60);x.setCurrentCount(0);x.setFinalDoneCount(0);x.setActivatedAt(Instant.now());x.setGapJson(gaps(owner,d,p));return x;}
 private List<DailyTaskEntity> generate(DailyPackageEntity p,LearningPlanEntity plan){List<DailyTaskEntity> result=new ArrayList<DailyTaskEntity>();int[] budget={p.getBudgetSeconds()};addMaterials(result,p,"action",materials.selectActions(p.getOwnerId(),1),budget);if(plan.getJournalEnabled()!=null&&plan.getJournalEnabled()==1)add(result,p,"journal","journal:"+p.getBusinessDate(),"今日复盘",null,budget,120);if(plan.getReviewEnabled()!=null&&plan.getReviewEnabled()==1)addMaterials(result,p,"review",materials.selectDueReviews(p.getOwnerId(),p.getBusinessDate(),plan.getReviewLimit()),budget);addMaterials(result,p,"tech",materials.selectContent(p.getOwnerId(),"tech",plan.getDifficulty(),plan.getTechCount()),budget);addMaterials(result,p,"word",materials.selectContent(p.getOwnerId(),"word",plan.getDifficulty(),plan.getNewWordCount()),budget);return result;}
 private void addMaterials(List<DailyTaskEntity> result,DailyPackageEntity p,String type,List<MaterialCandidate> candidates,int[] budget){for(MaterialCandidate candidate:candidates){String key=type+":"+candidate.getId();if(add(result,p,type,key,candidate.getTitle(),candidate,budget,candidate.getEstimatedSeconds()))continue;break;}}
 private boolean add(List<DailyTaskEntity> result,DailyPackageEntity p,String type,String key,String title,MaterialCandidate candidate,int[] budget,int seconds){if(seconds>budget[0])return false;DailyTaskEntity t=new DailyTaskEntity();t.setId(CryptoUtils.randomId());t.setOwnerId(p.getOwnerId());t.setPackageId(p.getId());t.setTaskType(type);t.setTitleSnapshot(title);t.setTargetKey(key);t.setStatus(DailyTaskStatus.TODO);t.setEstimatedSeconds(seconds);t.setSortNo(result.size()+1);t.setVersionNo(1);if(candidate!=null){if("tech".equals(type)||"word".equals(type))t.setContentId(candidate.getId());else if("review".equals(type))t.setKnowledgeId(candidate.getId());else if("action".equals(type))t.setActionId(candidate.getId());}result.add(t);budget[0]-=seconds;return true;}
 private DailyTaskEntity find(List<DailyTaskEntity> all,DailyTaskEntity expected){for(DailyTaskEntity task:all)if(task.getTaskType().equals(expected.getTaskType())&&task.getTargetKey().equals(expected.getTargetKey()))return task;return null;}
 private boolean contains(List<DailyTaskEntity> all,DailyTaskEntity expected){return find(all,expected)!=null;}
 private void cancel(DailyTaskEntity t){t.setStatus(DailyTaskStatus.CANCELLED);t.setCancelReason("user_remove");t.setVersionNo(t.getVersionNo()+1);tasks.updateById(t);}
 private void reopen(DailyTaskEntity t){t.setStatus(DailyTaskStatus.TODO);t.setCancelReason(null);t.setVersionNo(t.getVersionNo()+1);tasks.updateById(t);}
 private void recordSystemEvent(DailyTaskEntity t,String type,DailyTaskStatus from,DailyTaskStatus to){TaskEventEntity e=new TaskEventEntity();e.setId(CryptoUtils.randomId());e.setOwnerId(t.getOwnerId());e.setTaskId(t.getId());e.setTaskVersion(t.getVersionNo());e.setEventType(type);e.setActorType("system");e.setFromStatus(from.name());e.setToStatus(to.name());e.setOccurredAt(Instant.now());e.setReason("计划保存后同步今日任务");packages.insertEvent(e);}
 private boolean active(LearningPlanEntity p,LocalDate d){if(p.getIsPaused()!=null&&p.getIsPaused()==1)return p.getPauseUntil()!=null&&d.isAfter(p.getPauseUntil());return (p.getWeekdaysMask()&(1<<(d.getDayOfWeek().getValue()-1)))!=0;}
 private String gaps(String owner,LocalDate date,LearningPlanEntity p){List<Map<String,Object>> r=new ArrayList<Map<String,Object>>();gap(r,"action",1,materials.selectActions(owner,1).size());if(p.getReviewEnabled()!=null&&p.getReviewEnabled()==1)gap(r,"review",p.getReviewLimit(),materials.selectDueReviews(owner,date,p.getReviewLimit()).size());gap(r,"tech",p.getTechCount(),materials.selectContent(owner,"tech",p.getDifficulty(),p.getTechCount()).size());gap(r,"word",p.getNewWordCount(),materials.selectContent(owner,"word",p.getDifficulty(),p.getNewWordCount()).size());try{return json.writeValueAsString(r);}catch(Exception e){throw new IllegalStateException(e);}}
 private void gap(List<Map<String,Object>> r,String type,Integer wanted,int found){if(wanted!=null&&wanted>found){Map<String,Object> x=new LinkedHashMap<String,Object>();x.put("taskType",type);x.put("gapCount",wanted-found);x.put("reason","素材不足");r.add(x);}}
 private DailyPackageView empty(LocalDate d,String m){DailyPackageView v=new DailyPackageView();v.setBusinessDate(d);v.setActive(false);v.setNonActiveDay(true);v.setState("none");v.setMessage(m);v.setCurrentCount(0);v.setDoneCount(0);v.setTasks(Collections.<DailyTaskView>emptyList());return v;}
 private DailyPackageView view(DailyPackageEntity p,List<DailyTaskEntity> ts){int all=0,done=0;List<DailyTaskView> result=new ArrayList<DailyTaskView>();for(DailyTaskEntity t:ts){if(t.getStatus()!=DailyTaskStatus.CANCELLED){all++;if(t.getStatus()==DailyTaskStatus.DONE)done++;}result.add(task(t));}DailyPackageView v=new DailyPackageView();v.setBusinessDate(p.getBusinessDate());v.setActive(true);v.setTemporary(p.getTemporary()!=null&&p.getTemporary()==1);v.setNonActiveDay(false);v.setState(p.getState());v.setOriginalCount(p.getOriginalCount());v.setCurrentCount(all);v.setDoneCount(done);v.setCompletionRate(all==0?null:Math.round(done*1000.0/all)/10.0);v.setTasks(result);try{v.setGaps(p.getGapJson()==null?Collections.emptyList():json.readValue(p.getGapJson(),new TypeReference<List<Map<String,Object>>>(){}));}catch(Exception e){v.setGaps(Collections.emptyList());}if(all==0)v.setMessage("暂无任务");return v;}
 private DailyTaskView task(DailyTaskEntity t){DailyTaskView v=new DailyTaskView();v.setId(t.getId());v.setTaskType(t.getTaskType());v.setTitle(t.getTitleSnapshot());v.setTargetKey(t.getTargetKey());v.setStatus(t.getStatus().name());v.setEstimatedSeconds(t.getEstimatedSeconds());v.setSortNo(t.getSortNo());v.setVersionNo(t.getVersionNo());return v;}
 private String snapshot(DailyPackageEntity p,List<DailyTaskEntity> ts){try{Map<String,Object> x=new LinkedHashMap<String,Object>();List<String> ids=new ArrayList<String>();for(DailyTaskEntity task:ts)ids.add(task.getId());x.put("planId",p.getPlanId());x.put("taskIds",ids);x.put("count",ts.size());x.put("budgetSeconds",p.getBudgetSeconds());return json.writeValueAsString(x);}catch(Exception e){throw new IllegalStateException(e);}}
 private String reason(String s){if(s==null||s.trim().isEmpty())return null;s=s.trim();if(s.length()>200)throw fail(HttpStatus.BAD_REQUEST,"INVALID_REASON","原因最多 200 个字符");return s;}
 private Transition transition(DailyTaskStatus f,String raw){String e=raw==null?"":raw.trim().toLowerCase(Locale.ROOT);if("start".equals(e)&&f==DailyTaskStatus.TODO)return new Transition(f,DailyTaskStatus.DOING,e);if("complete".equals(e)&&f==DailyTaskStatus.DOING)return new Transition(f,DailyTaskStatus.DONE,e);if("skip".equals(e)&&(f==DailyTaskStatus.TODO||f==DailyTaskStatus.DOING))return new Transition(f,DailyTaskStatus.SKIPPED,e);if("undo".equals(e)&&f==DailyTaskStatus.DONE)return new Transition(f,DailyTaskStatus.DOING,e);throw fail(HttpStatus.BAD_REQUEST,"INVALID_TASK_TRANSITION","当前任务状态不允许该操作");}
 private ApiException fail(HttpStatus s,String c,String m){return new ApiException(s,c,m);} private static class Transition{final DailyTaskStatus from,to;final String event;Transition(DailyTaskStatus f,DailyTaskStatus t,String e){from=f;to=t;event=e;}}
}
