package com.zhixing.service;
import com.fasterxml.jackson.core.type.TypeReference;import com.fasterxml.jackson.databind.ObjectMapper;import com.zhixing.common.*;import com.zhixing.dto.ResourceScheduleRequest;import com.zhixing.entity.ResourceScheduleEntity;import com.zhixing.mapper.ResourceScheduleMapper;import com.zhixing.model.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.*;import java.util.*;
@Service
public class ResourceScheduleService {
 private static final ZoneId ZONE=ZoneId.of("Asia/Shanghai");private final ResourceScheduleMapper schedules;private final ObjectMapper json;
 public ResourceScheduleService(ResourceScheduleMapper s,ObjectMapper j){schedules=s;json=j;}
 public List<ResourceScheduleView> list(String ownerId,String state){List<ResourceScheduleView> rows=schedules.selectViews(ownerId,state);for(ResourceScheduleView v:rows)decorate(v);return rows;}
 public ResourceScheduleView get(String ownerId,String id){ResourceScheduleView v=schedules.selectView(ownerId,id);if(v==null)throw new ApiException(HttpStatus.NOT_FOUND,"SCHEDULE_NOT_FOUND","定时任务不存在");decorate(v);return v;}
 public List<ResourceSourceView> sources(){return schedules.selectSources();}
 @Transactional public ResourceScheduleView save(String ownerId,String id,ResourceScheduleRequest r){Prepared p=prepare(r);Instant now=Instant.now();if(id==null){ResourceScheduleEntity e=new ResourceScheduleEntity();e.setId(CryptoUtils.randomId());e.setOwnerId(ownerId);e.setName(p.name);e.setResourceKind(p.kind);e.setKeywords(p.keywords);e.setWeekdaysMask(p.mask);e.setMinuteOfDay(p.minute);e.setTimezone("Asia/Shanghai");e.setPerRunLimit(p.limit);e.setState(p.state);e.setNextRunAt(next(p.mask,p.minute,p.state));e.setVersionNo(1);e.setDedupEnabled(p.dedup);e.setSummaryEnabled(p.summary);e.setTopicsJson(write(p.topics));schedules.insert(e);id=e.getId();}else{ResourceScheduleEntity current=schedules.selectOwnedForUpdate(ownerId,id);if(current==null)throw new ApiException(HttpStatus.NOT_FOUND,"SCHEDULE_NOT_FOUND","定时任务不存在");if(r.getExpectedVersion()==null||!r.getExpectedVersion().equals(current.getVersionNo()))throw new ApiException(HttpStatus.CONFLICT,"SCHEDULE_VERSION_CONFLICT","定时任务已更新，请刷新后重试");if(schedules.updateSchedule(id,ownerId,p.name,p.kind,p.keywords,p.mask,p.minute,p.limit,p.state,next(p.mask,p.minute,p.state),p.dedup,p.summary,write(p.topics),now,current.getVersionNo())!=1)throw new ApiException(HttpStatus.CONFLICT,"SCHEDULE_VERSION_CONFLICT","定时任务已更新，请刷新后重试");}
  schedules.deleteSources(id);for(String sourceId:p.sourceIds)schedules.insertSource(CryptoUtils.randomId(),id,sourceId,now);return get(ownerId,id);
 }
 @Transactional public ResourceScheduleView state(String ownerId,String id,String state,Integer version){if(!Arrays.asList("active","paused").contains(state))throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_STATE","任务状态不合法");ResourceScheduleEntity current=schedules.selectOwnedForUpdate(ownerId,id);if(current==null)throw new ApiException(HttpStatus.NOT_FOUND,"SCHEDULE_NOT_FOUND","定时任务不存在");if(version==null||!version.equals(current.getVersionNo()))throw new ApiException(HttpStatus.CONFLICT,"SCHEDULE_VERSION_CONFLICT","定时任务已更新，请刷新后重试");if(schedules.updateState(id,ownerId,state,next(current.getWeekdaysMask(),current.getMinuteOfDay(),state),Instant.now(),version)!=1)throw new ApiException(HttpStatus.CONFLICT,"SCHEDULE_VERSION_CONFLICT","定时任务已更新，请刷新后重试");return get(ownerId,id);}
 private void decorate(ResourceScheduleView v){v.setSourceIds(schedules.selectSourceIds(v.getId()));v.setSourceNames(schedules.selectSourceNames(v.getId()));try{v.setTopics(v.getTopicsJson()==null?new ArrayList<String>():json.readValue(v.getTopicsJson(),new TypeReference<List<String>>(){}));}catch(Exception ignored){v.setTopics(new ArrayList<String>());}}
 private Prepared prepare(ResourceScheduleRequest r){Prepared p=new Prepared();p.name=trim(r.getName());if(p.name==null||p.name.codePointCount(0,p.name.length())>20)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_NAME","任务名称需为 1 至 20 个字符");p.kind="photo".equals(r.getResourceKind())?"photo":"resource";p.keywords=trim(r.getKeywords());p.topics=unique(r.getTopics());if(p.keywords==null)p.keywords=String.join(",",p.topics);if(p.keywords.length()>500)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_KEYWORDS","关键词最多 500 个字符");p.sourceIds=unique(r.getSourceIds());if(p.sourceIds.isEmpty())throw new ApiException(HttpStatus.BAD_REQUEST,"SCHEDULE_SOURCE_REQUIRED","至少选择一个公开来源");p.mask=r.getWeekdaysMask()==null?127:r.getWeekdaysMask();if(p.mask<1||p.mask>127)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_DAYS","执行日期不合法");p.minute=r.getMinuteOfDay()==null?420:r.getMinuteOfDay();if(p.minute<0||p.minute>1439)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_TIME","执行时间不合法");p.limit=r.getPerRunLimit()==null?5:r.getPerRunLimit();if(p.limit<1||p.limit>50)throw new ApiException(HttpStatus.BAD_REQUEST,"INVALID_SCHEDULE_LIMIT","每次收集上限为 1 至 50 条");p.state="paused".equals(r.getState())?"paused":"active";p.dedup=Boolean.FALSE.equals(r.getDedupEnabled())?0:1;p.summary=Boolean.TRUE.equals(r.getSummaryEnabled())?1:0;return p;}
 private Instant next(int mask,int minute,String state){if(!"active".equals(state))return null;ZonedDateTime cursor=ZonedDateTime.now(ZONE).withHour(minute/60).withMinute(minute%60).withSecond(0).withNano(0);if(!cursor.isAfter(ZonedDateTime.now(ZONE)))cursor=cursor.plusDays(1);for(int i=0;i<8;i++){int bit=cursor.getDayOfWeek().getValue()-1;if((mask&(1<<bit))!=0)return cursor.toInstant();cursor=cursor.plusDays(1);}return null;}
 private List<String> unique(List<String> values){LinkedHashSet<String> set=new LinkedHashSet<String>();if(values!=null)for(String raw:values){String v=trim(raw);if(v!=null)set.add(v);}return new ArrayList<String>(set);}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new ApiException(HttpStatus.INTERNAL_SERVER_ERROR,"SERIALIZATION_FAILED","配置保存失败");}}
 private String trim(String v){return v==null||v.trim().isEmpty()?null:v.trim();}
 private static class Prepared{String name,kind,keywords,state;int mask,minute,limit,dedup,summary;List<String> topics,sourceIds;}
}
