<script setup>
import { computed, onMounted, ref } from 'vue'
import { request } from '../../services/request.js'
const loading=ref(true),error=ref(''),data=ref({})
const completionRate=computed(()=>data.value.todayTasks?Math.round(Number(data.value.todayCompleted||0)*100/Number(data.value.todayTasks)):0)
async function load(){loading.value=true;error.value='';try{data.value=await request('/admin/overview')}catch(e){error.value=e.message||'概览加载失败'}finally{loading.value=false}}
function pricingText(){const value=data.value.pricing||{};return value.lastStatus==='success'?'同步正常':value.lastStatus==='failed'?'同步失败，沿用上一版本':'等待首次同步'}
function time(value){if(!value)return '—';return new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))}
onMounted(load)
</script>
<template><section><div class="page-heading"><div><h1>概览</h1><p>用户、内容、今日学习与 AI 运行状态汇总；统计日期 {{data.businessDate||'—'}}。</p></div><button class="refresh" :disabled="loading" @click="load">↻ 刷新</button></div><div v-if="loading" class="panel state">正在汇总运营数据…</div><div v-else-if="error" class="panel state error">{{error}}</div><template v-else><div class="metrics"><div class="panel metric"><span>正常用户</span><strong>{{data.activeUsers}}</strong><small>当前可使用账号</small></div><div class="panel metric"><span>已发布内容</span><strong>{{data.publishedContent}}</strong><small>{{data.publishedWords}} 单词 · {{data.publishedArticles}} 短文</small></div><div class="panel metric"><span>今日任务</span><strong>{{data.todayCompleted}} / {{data.todayTasks}}</strong><small>完成率 {{completionRate}}%</small></div><div class="panel metric"><span>待处理事项</span><strong>{{data.openFeedback}}</strong><small>用户反馈 · 可用邀请码 {{data.availableInvites}}</small></div></div><div class="grid"><article class="panel progress-card"><header><div><h2>今日学习进度</h2><p>只统计已生成的当日任务</p></div><b>{{completionRate}}%</b></header><div class="track"><i :style="{width:completionRate+'%'}"></i></div><footer><span>完成 {{data.todayCompleted}}</span><span>剩余 {{Math.max(0,(data.todayTasks||0)-(data.todayCompleted||0))}}</span></footer></article><article class="panel ai-card"><header><div><h2>AI 价格同步</h2><p>DeepSeek 官网 · 每天 22:00</p></div><span :class="['pill',data.pricing?.lastStatus]">{{pricingText()}}</span></header><dl><div><dt>最近检查</dt><dd>{{time(data.pricing?.lastCheckedAt)}}</dd></div><div><dt>本月已结算</dt><dd>{{data.monthAiSpend||0}} CNY</dd></div><div><dt>时区</dt><dd>{{data.pricing?.timezone||'Asia/Shanghai'}}</dd></div></dl></article></div></template></section></template>
<style scoped>.refresh{height:38px;padding:0 16px;border:1px solid #cfdcf0;border-radius:8px;color:#126ff4;background:#fff}.state{margin-top:24px;padding:60px;text-align:center;color:#77849a}.state.error{color:#bf3e49}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:16px;margin-top:24px}.metric{padding:20px}.metric span,.metric strong,.metric small{display:block}.metric span{color:#71809a;font-size:12px}.metric strong{margin-top:9px;color:#12214a;font-size:28px}.metric small{margin-top:8px;color:#7f8ba0}.grid{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin-top:18px}.progress-card,.ai-card{padding:22px}.grid header{display:flex;align-items:flex-start;justify-content:space-between}.grid h2{margin:0;font-size:18px}.grid p{margin:6px 0 0;color:#78859c;font-size:12px}.grid header>b{color:#0d6ff5;font-size:25px}.track{height:9px;margin-top:28px;overflow:hidden;border-radius:99px;background:#e8edf5}.track i{display:block;height:100%;border-radius:99px;background:#1476f7}.progress-card footer{display:flex;justify-content:space-between;margin-top:12px;color:#70809b;font-size:12px}.pill{padding:5px 9px;border-radius:99px;color:#7a8598;background:#eef1f5;font-size:11px}.pill.success{color:#0d805d;background:#e7f8f1}.pill.failed{color:#bf3e49;background:#fff0f1}.ai-card dl{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:24px 0 0}.ai-card dl div{padding:12px;border-radius:9px;background:#f7f9fd}.ai-card dt{color:#7d899f;font-size:11px}.ai-card dd{margin:6px 0 0;color:#223153;font-size:13px}@media(max-width:1100px){.metrics{grid-template-columns:repeat(2,1fr)}.grid{grid-template-columns:1fr}}</style>
