const { journalService } = require('../../../services/index');
const { formatDate, formatChineseDate } = require('../../../utils/date');

Page({
  data: { loading: true, saving: false, submitting: false, saveState: '', date: '', dateText: '', versionNo: 0, state: 'draft', form: { doneText: '', blockerText: '', learnedText: '', nextStepText: '' }, counts: {} },
  onLoad(options) { const date = options.date || formatDate(new Date()); this.cacheKey = `journal_draft_${date}`; this.setData({ date, dateText: date === formatDate(new Date()) ? formatChineseDate(new Date()) : date }); this.load(); },
  onUnload() { clearTimeout(this.localTimer); clearTimeout(this.syncTimer); this.saveLocal(); },
  load() { this.setData({ loading: true }); journalService.get(this.data.date).then((journal) => { const local = wx.getStorageSync(this.cacheKey); const form = local && local.versionNo === journal.versionNo ? local.form : { doneText: journal.doneText || '', blockerText: journal.blockerText || '', learnedText: journal.learnedText || '', nextStepText: journal.nextStepText || '' }; this.setData({ loading: false, versionNo: journal.versionNo, state: journal.state, form, counts: this.counts(form), saveState: journal.state === 'submitted' ? '已提交' : '已同步' }); }).catch((error) => { this.setData({ loading: false }); wx.showToast({ title: error.message || '复盘加载失败', icon: 'none' }); }); },
  input(e) { const key = e.currentTarget.dataset.key; const form = Object.assign({}, this.data.form, { [key]: e.detail.value }); this.setData({ form, counts: this.counts(form), saveState: '编辑中' }); clearTimeout(this.localTimer); clearTimeout(this.syncTimer); this.localTimer = setTimeout(() => this.saveLocal(), 2000); this.syncTimer = setTimeout(() => this.saveDraft(false), 5000); },
  counts(form) { return { doneText: form.doneText.length, blockerText: form.blockerText.length, learnedText: form.learnedText.length, nextStepText: form.nextStepText.length }; },
  payload() { return Object.assign({ expectedVersion: this.data.versionNo }, this.data.form); },
  saveLocal() { if (!this.cacheKey) return; wx.setStorageSync(this.cacheKey, { versionNo: this.data.versionNo, form: this.data.form }); this.setData({ saveState: '已保存到本地' }); },
  manualSave() { this.saveDraft(true); },
  saveDraft(showToast) { if (this.data.saving || this.data.submitting) return Promise.resolve(); this.setData({ saving: true, saveState: '同步中' }); return journalService.save(this.data.date, this.payload()).then((journal) => { this.apply(journal); if (showToast) wx.showToast({ title: '草稿已保存', icon: 'success' }); }).catch((error) => this.handleError(error)).finally(() => this.setData({ saving: false })); },
  submit() { if (this.data.submitting) return; clearTimeout(this.syncTimer); this.setData({ submitting: true }); journalService.submit(this.data.date, this.payload()).then((journal) => { this.apply(journal); wx.removeStorageSync(this.cacheKey); wx.showToast({ title: '复盘已提交', icon: 'success' }); setTimeout(() => wx.navigateBack(), 900); }).catch((error) => this.handleError(error)).finally(() => this.setData({ submitting: false })); },
  apply(journal) { this.setData({ versionNo: journal.versionNo, state: journal.state, saveState: journal.state === 'submitted' ? '已提交' : '已同步' }); wx.setStorageSync(this.cacheKey, { versionNo: journal.versionNo, form: this.data.form }); },
  handleError(error) { if (error.code === 'JOURNAL_VERSION_CONFLICT') { wx.showModal({ title: '服务器已有更新', content: '当前输入已保存在本地。你可以先复制本地稿，再重新加载服务器版本。', confirmText: '重新加载', cancelText: '复制本地稿', success: (result) => { if (result.confirm) this.load(); else wx.setClipboardData({ data: Object.values(this.data.form).join('\n\n') }); } }); return; } wx.showToast({ title: error.message || '保存失败', icon: 'none' }); }
});
